# Generated by Django 5.0.3 on 2024-03-17 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_address_user_city_user_country_user_county"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="round_numverts",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
