# Generated by Django 5.0.3 on 2024-03-17 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_round_numverts"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="round_numverts",
            new_name="round_number",
        ),
    ]
