# Generated by Django 5.0.3 on 2024-03-17 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="paid",
        ),
        migrations.AddField(
            model_name="payment",
            name="total_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
        migrations.AlterField(
            model_name="payment",
            name="meri_go_round_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
        migrations.AlterField(
            model_name="payment",
            name="savings_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
    ]
