# Generated by Django 5.0.3 on 2024-03-17 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0003_membersaving_payment_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membersaving",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Paid", "Paid"),
                    ("Defaulted", "Defaulted"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Pending",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="merigoroundpayment",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Paid", "Paid"),
                    ("Defaulted", "Defaulted"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Pending",
                max_length=255,
            ),
        ),
    ]
