# Generated by Django 5.0.3 on 2024-03-18 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0005_chamafine"),
    ]

    operations = [
        migrations.AddField(
            model_name="membersaving",
            name="amount_fined",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
    ]
