# Generated by Django 5.0.3 on 2024-03-19 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0006_membersaving_amount_fined"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="amount_fined",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
        migrations.AddField(
            model_name="payment",
            name="chama_amount",
            field=models.DecimalField(decimal_places=2, default=1500, max_digits=100),
        ),
        migrations.AddField(
            model_name="payment",
            name="closed",
            field=models.BooleanField(default=False),
        ),
    ]
