# Generated by Django 5.0.6 on 2024-08-13 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0010_alter_chamafine_member_alter_membersaving_member_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chamafine",
            name="status",
            field=models.CharField(
                choices=[
                    ("Approved", "Approved"),
                    ("Refunded", "Refunded"),
                    ("Disputed", "Disputed"),
                ],
                default="Approved",
                max_length=255,
            ),
        ),
    ]
