# Generated by Django 5.0.6 on 2024-08-13 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0011_chamafine_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chamafine",
            name="status",
            field=models.CharField(
                choices=[
                    ("Approved", "Approved"),
                    ("Refunded", "Refunded"),
                    ("Disputed", "Disputed"),
                    ("Settled", "Settled"),
                ],
                default="Approved",
                max_length=255,
            ),
        ),
    ]
