# Generated by Django 5.1.1 on 2024-09-06 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0013_membersaving_redeemed_groupedsaving_and_more"),
        ("savings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membersaving",
            name="saving",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="savings.groupedsaving",
            ),
        ),
        migrations.DeleteModel(
            name="GroupedSaving",
        ),
    ]
