# Generated by Django 5.0.3 on 2024-03-21 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loan",
            name="amount_awarded",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
    ]
