# Generated by Django 5.0.3 on 2024-03-21 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0002_alter_loan_amount_awarded"),
    ]

    operations = [
        migrations.AddField(
            model_name="loan",
            name="amount_to_repay",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
    ]
