# Generated by Django 5.0.6 on 2024-08-13 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0006_alter_loanpayment_loan_alter_loanpayment_member"),
    ]

    operations = [
        migrations.AddField(
            model_name="loanpayment",
            name="balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
    ]
