# Generated by Django 5.0.6 on 2024-08-13 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0007_loanpayment_balance"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoanType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "interest_rate",
                    models.DecimalField(decimal_places=2, max_digits=100),
                ),
                (
                    "min_amount",
                    models.DecimalField(decimal_places=2, default=100, max_digits=100),
                ),
                (
                    "max_amount",
                    models.DecimalField(
                        decimal_places=2, default=1000000000, max_digits=100
                    ),
                ),
                ("period", models.IntegerField(default=30)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
