# Generated by Django 5.0.6 on 2024-08-13 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0008_loantype"),
    ]

    operations = [
        migrations.AddField(
            model_name="loan",
            name="load_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="loans.loantype",
            ),
        ),
    ]
